---
name: build
on:
  pull_request:
    branches:
      - main

# Recommended by https://github.com/JamesIves/github-pages-deploy-action
permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  build:
    runs-on: ubuntu-latest
    container: node:20
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Generate all static pages.
        run: ./scripts/build.sh
      - name: Install, build, and upload your site output
        uses: withastro/action@v2
