---
name: test
on:
  pull_request:
    branches:
      - main

# Recommended by https://github.com/JamesIves/github-pages-deploy-action
jobs:
  test:
    runs-on: ubuntu-latest
    container: node:20
    steps:
      - uses: actions/checkout@v4
      - name: Install all dependencies.
        run: npm install
      - name: Check formatting
        run: npm run prettier:check
      - name: Install playwright with chromium
        run: npx playwright install --with-deps chromium
      - name: Run tests
        run: npm test
